Revert "runqueue: Print output for mismatched shared work tasks"
Issue: LIN7-3778

This reverts commit 0fe9a65f45cc1a7db545e2f3f668226747501303.

The commit causes a build error
ERROR: Mismatch /../oe-core/meta/recipes-devtools/gcc/gcc-source_4.9.bb,
do_build (6910363b68e12889f0ebf79233690690) compared to virtual:multilib:
lib32:/../oe-core/meta/recipes-devtools/gcc/gcc-source_4.9.bb, do_build
(c4ed5fb722225b697ec027e3438f47d0)